### ISSUE TITLE
LICENSE + contributions

### ISSUE THREAD

**Issue by ahmadsalim** [djspiewak/gll-combinators#26]
I am starting to use your library for a small parser of mine*, and I was wondering what license your project uses (if any, or if it is possible to add a license)?

Also, is there any procedure for submitting contributions? I have some small things, which may be useful to add to the library.

* I wanted to try GLL parsing out since I thought it was an interesting idea.

**Comment by djspiewak** [comment]
Sorry for the delay on responding to this.  I… don't appear to have put a license in the codebase anywhere!  That's a mistake.  Consider the sources to be under the Apache 2 license; I'll be adding the license file today.

Regarding contributions, the best way is via pull request.  Contributions that improve the library, particularly those that do so without adding bloat, are extremely welcome.
